import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers'
 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Athena Beta",
  description: "Generated by create next app",
};


export const viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>       
      <div className="flex flex-col min-h-screen">     
      <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <main className="flex flex-col flex-1 bg-muted/50">{children}</main>
        </Providers>
        </div>
      </body>
    </html>
  );
}
